// angular spring boot/Angular_crud/src/app/showallcustomer/showallcustomer.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { CustomerService } from '../service/customer.service';
import { Observable } from 'rxjs';
import { Customer } from '../model/customer';
import { Router } from '@angular/router';

@Component({
  selector: 'app-showallcustomer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './showallcustomer.component.html',
  styleUrl: './showallcustomer.component.css'
})
export class ShowallcustomerComponent {
   customer: Observable<Customer[]>

  constructor(service:CustomerService, private router:Router){
    this.customer=service.getAllCustomer();
  }


  addcustomer(){
    this.router.navigate(['/add'])
  }

}

<div class="container">
 <h1>All Customer Detail </h1>
  <table class="table table-bordered table-striped bg-primary text-light">
  <thead>
    <tr>
        <th>Customer Id</th>
        <th>Customer Name</th>
        <th>Customer Salary</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let c of customer|async">
     <td>
        {{c.customerId}}
     </td>
     <td>
        {{c.customerName}}
     </td>
     <td>
        {{c.customerSalary}}
     </td>

    </tr>
  </tbody>
 </table>
 <button (click)="addcustomer()">Add Customer page</button>
</div>

// kafka1/react 18 route v6.21/navigation and axios/react_main/src/Customer_Hook/ShowAllCustomer.js
import { useEffect, useState } from "react";
import CustomerService from "./services/CustomerService";
import { useNavigate } from "react-router-dom";
const ShowAllCustomer = () => {
    const [customer, getAllCustomer] = useState([]);
    const navigate = useNavigate();

    useEffect(() => {
        new CustomerService().getAllCustomer()
            .then(response => {
                getAllCustomer(response.data)
            })
            .catch(e => {
                console.log(e);
            })
    }, [])

    return (
        <div className="container bg-secondary text-warning p-5  w-50 mt-5" style={{ 'marginLeft': '200 pt' }}>
            <h1>all customer</h1>
            <table className="table table-striped table-bordered" >
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>salary</th>
                </tr>
                {
                    customer.map(cust =>
                        <tr>
                            <td>{cust.customerId}</td>
                            <td>{cust.customerName}</td>
                            <td>{cust.customerSalary}</td>
                        </tr>
                    )
                }
            </table>
            <button type="button" className="btn btn-primary" onClick={(a) =>
                navigate('/searchbyid')
            }>Search By Id</button>
        </div>
    )
}
export default ShowAllCustomer;
