// react/app1/src/crud/AddBook.js
import axios from "axios"
import { useEffect, useState } from "react"

export const AddBook = () => {
  const  [msg,setMsg] =useState('')
   const [book,setBook] =useState({})
   const [error,setError] =useState({})

    const submit=(event)=>{
        event.preventDefault();
        console.log(JSON.stringify(book))
        axios.post("http://localhost:9090/book",book).then(resp=>{
            const data=resp.data
            setMsg("record added "+JSON.stringify(data))
            alert('record added ')
        }).catch(error=>{
            const errorMsg = error.response?.data || error.message;
            setError(errorMsg)
        })
    }
    return (
        <div className="container border border-info m-5 p-5 w-100 bg-warning">
            <form onSubmit={submit}>
                <div className="row md-3">
                    <label className="col-3">enter name</label>
                    <input className="col-6"  onChange={(e)=>{
                        const value=e.target.value
                        setBook({...book,bname:value})
                        if(value=='')
                            setError({...error,bname:'name is blank'})
                        else 
                        setError({...error,bname:''})

                    }}></input>
                   <span className="col-3 text-danger"> {error.bname && <>{error.bname}</>}</span>
                </div>

                <div className="row md-3 mt-1">
                    <label className="col-3">enter cost</label>
                    <input className="col-6" onChange={(e)=>{
                        const value=e.target.value
                        setBook({...book,cost:value})
                        if(value=='')
                            setError({...error,cost:'cost is blank'})
                        else 
                        setError({...error,cost:''})

                    }}></input>
                   <span className="col-3 text-danger"> {error.cost && <>{error.cost}</>}</span>

                </div>

                <div className="mt-2">
                    <button type="submit" className="btn btn-success">add record</button>
                    <button type="reset" className="btn btn-success ms-1">cancel</button>
                </div>
            </form>
           <>{msg && <>{msg}</>}</>
        </div>
    )
}
// export default AddBook;

// angular/app3/src/app/crud/add-book/add-book.component.ts
import { Component, Input } from '@angular/core';
import { BookService } from '../service/book.service';
import { Book } from '../model/Book';


@Component({
  selector: 'app-add-book',
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.css']
})
export class AddBookComponent {
  @Input() book: Book;
  msg: string = '';

  constructor(private service: BookService) {
    this.book = new Book();
    console.log('constructor book is ' + this.book)
  }

  addBook() {
    // this.service.addBook(this.book).subscribe(data => this.msg = 'record added', error => {
    //   this.msg = error
    //   //console.log("error is " + error.error)
    //   console.log("error is " + error)
    // });

    this.service.addBook(this.book).subscribe();

  }

}

<div class="container">
    <h2>Book Add Form</h2>
    <form (ngSubmit)="addBook()">
        <div class="form-group">
            <label>Enter Id</label>
            <input class="form-control" name="prdId" [(ngModel)]="book.isbn" ngModel="isbn">
        </div>
        <div class="form-group">
            <label>Enter Name</label>
            <input class="form-control" name="prdName" [(ngModel)]="book.bname" ngModel="bname">
        </div>
        <div class="form-group">
            <label>Enter Cost</label>
            <input class="form-control" name="prdCost" [(ngModel)]="book.cost" ngModel="cost">
        </div>

        <div class="form-group">
            <input class="form-control" type="submit" value="Add Book">
            <input class="form-control" type="reset" value="Cancel">
        </div>
    </form>
    <div>
        {{msg}}
    </div>
</div>
