// angular/app3/src/app/crud/add-book/add-book.component.ts
import { Component, Input } from '@angular/core';
import { BookService } from '../service/book.service';
import { Book } from '../model/Book';


@Component({
  selector: 'app-add-book',
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.css']
})
export class AddBookComponent {
  @Input() book: Book;
  msg: string = '';

  constructor(private service: BookService) {
    this.book = new Book();
    console.log('constructor book is ' + this.book)
  }

  addBook() {
    // this.service.addBook(this.book).subscribe(data => this.msg = 'record added', error => {
    //   this.msg = error
    //   //console.log("error is " + error.error)
    //   console.log("error is " + error)
    // });

    this.service.addBook(this.book).subscribe();

  }

}

<div class="container">
    <h2>Book Add Form</h2>
    <form (ngSubmit)="addBook()">
        <div class="form-group">
            <label>Enter Id</label>
            <input class="form-control" name="prdId" [(ngModel)]="book.isbn" ngModel="isbn">
        </div>
        <div class="form-group">
            <label>Enter Name</label>
            <input class="form-control" name="prdName" [(ngModel)]="book.bname" ngModel="bname">
        </div>
        <div class="form-group">
            <label>Enter Cost</label>
            <input class="form-control" name="prdCost" [(ngModel)]="book.cost" ngModel="cost">
        </div>

        <div class="form-group">
            <input class="form-control" type="submit" value="Add Book">
            <input class="form-control" type="reset" value="Cancel">
        </div>
    </form>
    <div>
        {{msg}}
    </div>
</div>

// web/react/crud_2026/crud2/app1_practice/src/database_fetch/AddBook.js
import axios from "axios"
import { useState } from "react"

export const AddBook = () => {
    const [error, setError] = useState(null)
    const [errors, setErrors] = useState({})
    const [loading, setLoading] = useState(true)
    const [book, setBook] = useState({})
    const [msg, setMsg] = useState('')

    const submit = (e) => {
        e.preventDefault();
        console.log(JSON.stringify(book))
        axios.post('http://localhost:8082/book', book).then(response => {
            setBook(response.data);
            
            setMsg('Record added ' + JSON.stringify(response.data)+"<p> status code :"+(response.status)+"</p>")
            setLoading(false)
        }).catch(e => {
            setError(e.message)
        }
        );  
    }
    return (
        <div className="container">
            <form onSubmit={submit} className="bg-info p-5 m-5">
                <div className="form-group">
                    <label>Enter Name</label>
                    <input className="form-control" onChange={(e) => {
                        const val = e.target.value
                        setBook({ ...book, name: val })
                        if (val == 0)
                            setErrors({ ...errors, name: "name is empty" })
                        else if (val.length < 5 || val.length > 20)
                            setErrors({ ...errors, name: "name must of 5 - 20 characters" })
                        else
                            setErrors({ ...errors, name: null })
                    }}></input>
                    {errors.name && <span className="text-danger">{errors.name}</span>}
                </div>

                <div className="form-group">
                    <label>Enter publish date</label>
                    <input type="date" className="form-control"
                        onChange={(e) => {
                            const val = e.target.value
                            setBook({ ...book, publishDate: val })
                            if (val == "")
                                setErrors({ ...errors, publishDate: 'date is empty' })
                            else setErrors({ ...errors, publishDate: null })
                        }}
                    ></input>
                    {errors.pdate && <span className="text-danger">{errors.pdate}</span>}
                </div>

                <div className="form-group">
                    <label>Enter Cost</label>
                    <input className="form-control" type="number" onChange={(e) => {
                        const val = e.target.value
                        setBook({ ...book, cost: val })
                        if (val == "")
                            setErrors({ ...errors, cost: 'cost is empty' })
                        else if (val <= 0)
                            setErrors({ ...errors, cost: 'cost is zero or -ve ' })
                        else
                            setErrors({ ...errors, cost: null })
                    }}></input>
                    {errors.cost && <span className="text-danger">{errors.cost}</span>}
                </div>
                <div>
                    <button type="submit" className="btn btn-secondary">Add Record </button>
                    <button type="reset" className="btn btn-secondary">Cancel</button>
                </div>
                {msg && <>{msg}</>}
            </form>
        </div>
    )

}
